# This is for Jujitsu version control and requires setup; see README.
[aliases]
build = [
    "!", "sh", "-c",
    '''
    # start by building Zig code...
    zig build -Doptimize=ReleaseSafe -Dgen-enums
    if [ $? -ne 0 ]; then
        echo "Error: Zig build failed; commit stopped."
        exit 1
    fi

    # now build NPM public/ files...
    npm run build
    if [ $? -ne 0 ]; then
        echo "Error: NPM build failed; commit stopped."
        exit 1
    fi
    '''
]