//! The portal descent: the animation that carries the player from depth D down into D+1.
//!
//! A descent runs entirely on a frame counter (`memory.game.portal_frame`) advanced by `handleTick()`,
//! never on wall time, so it plays back identically at any frame rate and can be resumed from a save.
//! The committed world stays at D for every frame but the last;
//! D+1 is only ever a preview, generated into a scratch buffer and drawn over D as it fades in.
const std = @import("std");
const dw = @import("../root.zig");

const memory = dw.memory;
const world = dw.world;
const Chunk = memory.Chunk;
const Sprite = dw.Sprite;
const Coordinate = world.Coordinate;
const Vec2f32 = dw.utils.Vec2f32;

/// Length of a descent; at 60fps this is a bit over one second.
pub const TOTAL_FRAMES: u32 = 120;
/// Frames the player takes to be drawn from where they stand into the portal's mouth.
pub const PULL_FRAMES: u32 = 24;

/// Relative zoom the D+1 overlay starts becoming visible at.
/// The preview must be fully generated by the time the zoom reaches this.
pub const OVERLAY_ZOOM: f64 = 1.5;

/// Baseline number of preview chunks generated per frame (increased if camera view is too big).
pub const CHUNKS_PER_FRAME: u32 = 4;

/// Frames the zoom must stay at or below `OVERLAY_ZOOM` for, giving the preview time to fill.
/// Asserted against the actual curve at the start of every descent rather than assumed.
///
/// This is only a floor on how thinly the work can be spread, not a correctness requirement:
/// `chunksPerFrame()` divides the buffer by the real deadline, so a shorter descent simply generates
/// more chunks per frame rather than showing an unfinished overlay.
pub const MIN_FILL_FRAMES: u32 = 30;

/// Half-width of the block window sampled for debris sprites, in blocks (so an 8x8 window).
pub const DEBRIS_RADIUS: i32 = 4;
/// Distinct block types collected from that window to draw from.
const MAX_PALETTE: usize = @intCast(4 * DEBRIS_RADIUS * DEBRIS_RADIUS);

/// How many shards a descent spawns. Each is one block sprite falling in from a ring around the portal.
/// They are drawn from the sampled palette, so a type shows up as many times as it happens to be picked.
const SHARD_COUNT: usize = 1024;

/// Fraction of the descent over which shards keep starting. Runs almost to the end so terrain is still
/// being drawn in as the zoom closes on `ZOOM_FACTOR`, rather than stopping partway.
const SHARD_SPAWN_SPAN: f64 = 0.9;

/// Frames one shard takes to reach the portal once it starts moving.
const SHARD_TRAVEL_MIN: u32 = 14;
const SHARD_TRAVEL_MAX: u32 = 28;

/// Screen-space ring, in viewport pixels, that shards drift in from.
/// Kept in screen space on purpose: it makes them immune to the zoom,
/// so they can keep being "swallowed" the whole way to `ZOOM_FACTOR`,
/// without anything having to be rescaled per frame.
const SHARD_RADIUS_MIN: f32 = 15.0;
const SHARD_RADIUS_MAX: f32 = 80.0;

/// Edge length of a shard in viewport pixels, before its per-shard jitter.
/// About half a block, so the debris reads as rubble rather than as loose terrain.
const SHARD_SIZE: f32 = @as(f32, dw.CHUNK_SIZE) / 2.0;

/// Blue-cyan tints for the intake particles. `.particle` is a white sprite,
/// so chroma and hue here are added straight onto it (see `DEFAULT_ENTITY_LCHA`); hue is in radians.
const PORTAL_COLORS = [_][4]f32{
    .{ 0.85, 0.16, 4.55, 1.0 },
    .{ 0.95, 0.13, 4.75, 1.0 },
    .{ 0.75, 0.19, 4.35, 1.0 },
    .{ 1.00, 0.10, 4.95, 1.0 },
};

comptime {
    if (PULL_FRAMES >= TOTAL_FRAMES) @compileError("The player must finish being drawn in before the descent lands.");
    if (OVERLAY_ZOOM <= 1.0 or OVERLAY_ZOOM >= dw.ZOOM_FACTOR) @compileError("OVERLAY_ZOOM must sit between 1x and ZOOM_FACTOR.");
}

/// Which transition is running. Stored in `GameState` as its integer tag.
pub const Phase = enum(u8) {
    idle,
    /// A D -> D+1 descent through a portal, shaped by `portal_frame`.
    descending,
    /// A D -> D-1 ascent through an inverted portal, the same animation run in reverse.
    ascending,
};

/// Whether the running transition is a descent (rather than an ascent). Only meaningful while active.
inline fn isDescending() bool {
    return memory.game.portal_phase == @intFromEnum(Phase.descending);
}

/// One block being swallowed: a purely visual echo of terrain near the player.
/// The world itself is never touched, so no modification is ever written for this.
///
/// Positioned on a ring around the portal rather than at the block's real location: the point is the
/// portal devouring its surroundings, and scattering the shards reads better than a literal 8x8 grid
/// marching in. A block type can therefore appear any number of times, or not at all.
const Shard = struct {
    sprite: Sprite,
    /// Direction it drifts in from, in radians.
    angle: f32,
    /// Distance from the portal it starts at, in viewport pixels.
    radius: f32,
    /// Edge length in viewport pixels.
    size: f32,
    /// Spin over its whole travel, in radians.
    spin: f32,
    start_frame: u32,
    /// Frames it takes to reach the portal.
    travel: u32,
};

/// The D+1 transition, worked out once when the descent starts and reinstalled every frame
/// the preview is generated under. Valid only while `ready` is set.
var transition: world.LayerTransition = undefined;

/// D+1 chunks covering everything the overlay can show, taken from `main_allocator`.
var preview: []Chunk = &.{};
/// The coordinate each `preview` slot holds, so a lookup can confirm it found the right chunk.
/// Needed because a window may straddle a quadrant boundary past the horizon,
/// where suffixes wrap and the quadrant flips; comparing suffix offsets alone would mismatch there.
var preview_keys: []Coordinate = &.{};

/// Chunk the grid is measured out from: where the player lands at D+1.
/// The grid is anchored here rather than on its own top-left corner, since that corner can fall off
/// the world (near an edge) and have no coordinate at all to anchor to.
var preview_centre: Coordinate = undefined;
/// Chunk offset of the grid's top-left cell from `preview_centre`.
var preview_min: [2]i32 = .{ 0, 0 };
var preview_w: u32 = 0;
var preview_h: u32 = 0;

/// How many slots of `preview` hold generated chunks; the rest are still blank.
var filled: u32 = 0;
/// Frame by which the preview must be complete, derived from where the zoom curve crosses `OVERLAY_ZOOM`.
var fill_deadline: u32 = MIN_FILL_FRAMES;

/// The point everything converges on, in subpixels relative to the player's chunk:
/// the spot inside the portal block that maps exactly onto where the player lands at D+1.
/// Zooming into it and then committing therefore lands on the very same world point, with nothing to jump.
var anchor: [2]f64 = .{ 0.0, 0.0 };

/// Where the shards and intake particles converge on (descent) or burst from (ascent), in subpixels
/// relative to the player's chunk. Always the (inverted) portal block; coincides with `anchor` for a
/// descent, but sits apart from it for an ascent, where the camera holds on the player instead.
var effect_centre: [2]f64 = .{ 0.0, 0.0 };

/// The descent's shards. Held in a fixed-sized array rather than a dynamic allocation.
var debris: [SHARD_COUNT]Shard = undefined;
/// How many shards are currently active in the array.
var debris_count: usize = 0;

/// Whether `transition`, `preview`, `anchor` and `debris` describe the descent `GameState` says is running.
/// Cleared by `reset()` and by a load, which is what makes `ensureReady()` rebuild them.
var ready: bool = false;

/// Whether a portal transition (descent or ascent) is currently playing.
pub inline fn isActive() bool {
    return memory.game.portal_phase != @intFromEnum(Phase.idle);
}

/// Smooth 0-1 ease with zero slope at both ends.
inline fn smoothstep(t: f64) f64 {
    const x = std.math.clamp(t, 0.0, 1.0);
    return x * x * (3.0 - 2.0 * x);
}

/// Mild ease-out that gently decelerates to a stop.
inline fn easeOut(t: f64) f64 {
    const x = std.math.clamp(t, 0.0, 1.0);
    return x * (2.0 - x);
}

/// How far through the descent we are, 0 at the first frame and 1 on the committing frame.
inline fn progress() f64 {
    return @as(f64, @floatFromInt(memory.game.portal_frame)) / @as(f64, @floatFromInt(TOTAL_FRAMES));
}

/// Exponent of the zoom at progress `t`, where the zoom is `ZOOM_FACTOR` raised to it.
///
/// Driving an exponent (rather than the zoom itself) makes each frame scale the view by a visually consistent ratio
/// (similar to how actual fractal zoom videos work)!
/// Squaring the smoothstep() keeps the slope at zero on both ends (so it eases in and out),
/// while holding the early frames low enough for the preview to finish generating before the overlay appears.
inline fn zoomCurve(t: f64) f64 {
    const s = smoothstep(t);
    return s * s;
}

/// Signed zoom exponent for this frame: a descent zooms in (+), an ascent zooms out (-).
inline fn zoomSign() f64 {
    return if (isDescending()) 1.0 else -1.0;
}

/// How much the world's zoom is multiplied by this frame.
/// A descent runs 1x -> `ZOOM_FACTOR` (zoom in); an ascent runs 1x -> `1 / ZOOM_FACTOR` (zoom out).
/// `overlayScale()` cancels the factor out, which is why reaching the last frame lands on the committed view.
pub fn zoomFactor() f64 {
    if (!isActive()) return 1.0;
    return std.math.pow(f64, @as(f64, dw.ZOOM_FACTOR), zoomSign() * zoomCurve(progress()));
}

/// The zoom multiplier at an arbitrary frame, for planning ahead of time.
fn zoomFactorAt(frame: u32) f64 {
    const t = @as(f64, @floatFromInt(frame)) / @as(f64, @floatFromInt(TOTAL_FRAMES));
    return std.math.pow(f64, @as(f64, dw.ZOOM_FACTOR), zoomSign() * zoomCurve(t));
}

/// Scale multiplier the overlay layer is drawn at, relative to `camera_scale`.
///
/// The overlay is the depth being ENTERED (D+1 descending, D-1 ascending), so it sits at a factor of
/// `ZOOM_FACTOR` from the live layer: descending it is `ZOOM_FACTOR` smaller, ascending `ZOOM_FACTOR`
/// larger. Either way the factor cancels `zoomFactor()` on the last frame, so the overlay arrives at
/// exactly `camera_scale` and the hand-off to the committed world is invisible.
pub fn overlayScale() f64 {
    const factor: f64 = if (isDescending()) 1.0 / @as(f64, dw.ZOOM_FACTOR) else dw.ZOOM_FACTOR;
    return zoomFactor() * factor;
}

/// Overlay scale at its most zoomed-out (widest footprint), which is what `allocatePreview()` sizes for.
/// Descending that is the instant it appears (`OVERLAY_ZOOM / ZOOM_FACTOR`); ascending it is the
/// committed frame (`1.0`), since the D-1 layer starts zoomed in and pulls out to rest.
fn widestOverlayScale() f64 {
    return if (isDescending()) OVERLAY_ZOOM / @as(f64, dw.ZOOM_FACTOR) else 1.0;
}

/// Zoom at which the overlay begins to reveal, driving `planFill()`'s deadline.
/// Mirrored for an ascent: instead of zooming past `OVERLAY_ZOOM` in, it zooms past its reciprocal out.
inline fn revealZoom() f64 {
    return if (isDescending()) OVERLAY_ZOOM else 1.0 / OVERLAY_ZOOM;
}

/// Whether `zoom` has passed the reveal threshold, accounting for the zoom direction.
inline fn pastReveal(zoom: f64) bool {
    return if (isDescending()) zoom > revealZoom() else zoom < revealZoom();
}

/// Opacity the D+1 layer (chunks and background alike) is drawn at.
///
/// D is never faded: it stays at full strength for the whole descent and this is the only knob moved,
/// so D+1 arrives *over* a solid image rather than the two meeting in the middle as a dissolve.
pub fn overlayOpacity() f64 {
    if (!isActive()) return 0.0;
    const start = zoomCurve(@as(f64, @floatFromInt(fill_deadline)) / @as(f64, @floatFromInt(TOTAL_FRAMES)));
    const now = zoomCurve(progress());
    if (now <= start) return 0.0;

    const t = easeOut((now - start) / (1.0 - start));
    return t * t;
}

/// How far the player has been drawn into the portal, 0 to 1.
/// Always 0 for an ascent: the player is not pulled anywhere, they zoom out from where they stand,
/// so the pull, squeeze and camera-ease terms that read this all fall out to identity.
inline fn pullProgress() f64 {
    if (!isDescending()) return 0.0;
    const frame: f64 = @floatFromInt(@min(memory.game.portal_frame, PULL_FRAMES));
    return frame / @as(f64, @floatFromInt(PULL_FRAMES));
}

/// How hard the world is shaking this frame, 0 (still) to 1 (full tremor).
/// Builds with the zoom so the tremor peaks as the descent commits (see `chunks.updateShake()`).
pub fn shakeIntensity() f32 {
    if (!isActive()) return 0.0;
    // A floor keeps a tremor present from the first frame, since the zoom curve starts flat.
    return @floatCast(0.25 + 0.75 * zoomCurve(progress()));
}

/// Rate the background clock advances at, eased to a standstill as the player is drawn in.
pub fn backgroundRate() f64 {
    if (!isActive()) return 1.0;
    return 1.0 - smoothstep(pullProgress());
}

/// Starts a descent through the portal at `coord`'s block (`bx`, `by`). Ignored if one is already running.
pub fn trigger(coord: Coordinate, bx: u4, by: u4) void {
    beginTransition(.descending, coord, bx, by);
}

/// Starts an ascent through the inverted portal at `coord`'s block (`bx`, `by`).
/// The block is recorded only so the effects can emanate from it; the transition itself derives
/// entirely from the player's position (see `world.computeParentLayer()`). Ignored if one is running.
pub fn triggerAscend(coord: Coordinate, bx: u4, by: u4) void {
    beginTransition(.ascending, coord, bx, by);
}

fn beginTransition(phase: Phase, coord: Coordinate, bx: u4, by: u4) void {
    if (isActive()) return;

    const g = &memory.game;
    g.portal_chunk = coord.suffix;
    g.portal_quadrant = coord.quadrant;
    g.portal_bx = bx;
    g.portal_by = by;
    g.portal_frame = 0;
    g.portal_phase = @intFromEnum(phase);

    ready = false;
    ensureReady();
}

/// The portal that started the running descent, as recorded in `GameState`.
inline fn portalCoord() Coordinate {
    return .{
        .suffix = memory.game.portal_chunk,
        .quadrant = @intCast(memory.game.portal_quadrant & 3),
    };
}

/// Works out everything a descent needs that a save does not carry.
/// Safe to call repeatedly; only the first call after a trigger (or a load) does any work.
fn ensureReady() void {
    if (ready or !isActive()) return;

    const bx: u4 = @intCast(memory.game.portal_bx & 15);
    const by: u4 = @intCast(memory.game.portal_by & 15);

    if (isDescending()) {
        // `.block_floor` pins the landing to the portal block itself. Deriving it from the player
        // instead would place them wherever they happened to be standing scaled up, which need not
        // even be inside the portal, and can land inside solid terrain.
        transition = world.computeLayer(portalCoord(), bx, by, .block_floor);
        computeAnchor(bx, by);
    } else {
        // An ascent keeps the player's own world point (see `world.computeParentLayer()`), so the
        // camera holds on the player and simply pulls out; the anchor is the player's own position.
        transition = world.computeParentLayer();
        anchor = .{
            @floatFromInt(memory.game.player_pos[0]),
            @floatFromInt(memory.game.player_pos[1]),
        };
    }
    // The effects always radiate from the (inverted) portal block, wherever the camera settles.
    computeEffectCentre(bx, by);

    planFill();
    allocatePreview();
    // A descent spreads generation over its length; an ascent's parent preview is smaller and cheaper,
    // so it is filled up front and no reveal deadline gates it.
    if (!isDescending()) fillPreview(@intCast(preview.len));
    collectDebris();
    ready = true;
}

/// Places `effect_centre` on the portal block, in subpixels relative to the player's chunk.
/// This is where shards and intake particles emanate from, for both directions.
fn computeEffectCentre(bx: u4, by: u4) void {
    const g = &memory.game;
    const portal = portalCoord();
    const player_coord = g.getPlayerCoord();
    const chunk_dx: i64 = @bitCast(portal.suffix[0] -% player_coord.suffix[0]);
    const chunk_dy: i64 = @bitCast(portal.suffix[1] -% player_coord.suffix[1]);
    const block: f64 = @floatFromInt(dw.CHUNK_SIZE_SQ);
    effect_centre = .{
        @as(f64, @floatFromInt(chunk_dx * dw.SUBPIXELS_IN_CHUNK)) + (@as(f64, @floatFromInt(bx)) + 0.5) * block,
        @as(f64, @floatFromInt(chunk_dy * dw.SUBPIXELS_IN_CHUNK)) + (@as(f64, @floatFromInt(by)) + 0.5) * block,
    };
}

/// Locates the D-space point matching where the player lands at D+1.
///
/// The landing sits at some offset inside the portal block's child region; dividing that offset by
/// `ZOOM_FACTOR` gives the same spot expressed in the parent block, which is what the camera has to
/// arrive at for the commit to be seamless.
fn computeAnchor(bx: u4, by: u4) void {
    const g = &memory.game;
    const player_coord = g.getPlayerCoord();
    const portal = portalCoord();

    // Wrapping subtraction gives the signed chunk delta, matching how `moveAtDepth()` steps.
    const chunk_dx: i64 = @bitCast(portal.suffix[0] -% player_coord.suffix[0]);
    const chunk_dy: i64 = @bitCast(portal.suffix[1] -% player_coord.suffix[1]);

    // Offset of the landing within its child region, brought back into parent-block scale.
    // Read off the transition rather than restated here, so the two can never disagree about where
    // the descent actually puts the player.
    const region: i64 = dw.CHUNK_SIZE_SQ * dw.ZOOM_FACTOR;
    const in_region_x: f64 = @floatFromInt(@mod(transition.new_pos[0], region));
    const in_region_y: f64 = @floatFromInt(@mod(transition.new_pos[1], region));

    const block: f64 = @floatFromInt(dw.CHUNK_SIZE_SQ);
    anchor = .{
        @as(f64, @floatFromInt(chunk_dx * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(bx)) * block + in_region_x / dw.ZOOM_FACTOR,
        @as(f64, @floatFromInt(chunk_dy * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(by)) * block + in_region_y / dw.ZOOM_FACTOR,
    };
}

/// Finds the last frame the zoom is still at or below `OVERLAY_ZOOM`,
/// which is the deadline the preview has to be complete by. Derived from the curve rather than hard-coded,
/// so retuning the timing cannot silently let the overlay appear over half-generated chunks.
fn planFill() void {
    fill_deadline = TOTAL_FRAMES;
    var frame: u32 = 0;
    while (frame <= TOTAL_FRAMES) : (frame += 1) {
        if (pastReveal(zoomFactorAt(frame))) {
            fill_deadline = frame;
            break;
        }
    }
    // An ascent generates its whole (smaller) parent preview up front in `ensureReady()`, so it has
    // no fill floor to honour; only a descent spreads generation and needs the assert.
    if (isDescending()) std.debug.assert(fill_deadline >= MIN_FILL_FRAMES);
}

/// Sizes and clears the D+1 preview to cover the widest view the overlay can ever show.
///
/// That widest view is the instant the overlay appears, at `OVERLAY_ZOOM`: the D+1 layer is drawn at
/// `zoomFactor() / ZOOM_FACTOR`, which only grows from there, so the footprint only ever shrinks.
fn allocatePreview() void {
    const g = &memory.game;
    // The scale the overlay layer is drawn at when its footprint is widest (its most zoomed-out state).
    const widest_zoom = g.camera_scale * widestOverlayScale();

    const subpixels_per_chunk: f64 = @floatFromInt(dw.SUBPIXELS_IN_CHUNK);
    const half_w_sp = (@as(f64, dw.SCREEN_WIDTH_HALF) / widest_zoom) * dw.CHUNK_SIZE;
    const half_h_sp = (@as(f64, dw.SCREEN_HEIGHT_HALF) / widest_zoom) * dw.CHUNK_SIZE;

    // The camera has arrived on the landing point by the time the overlay shows so D+1 is centered!
    const cam_x: f64 = @floatFromInt(transition.new_pos[0]);
    const cam_y: f64 = @floatFromInt(transition.new_pos[1]);

    const margin: i32 = @intCast(dw.lighting.CHUNK_MARGIN);
    const min_cx = @as(i32, @intFromFloat(@floor((cam_x - half_w_sp) / subpixels_per_chunk))) - margin;
    const min_cy = @as(i32, @intFromFloat(@floor((cam_y - half_h_sp) / subpixels_per_chunk))) - margin;
    const max_cx = @as(i32, @intFromFloat(@floor((cam_x + half_w_sp) / subpixels_per_chunk))) + margin;
    const max_cy = @as(i32, @intFromFloat(@floor((cam_y + half_h_sp) / subpixels_per_chunk))) + margin;

    const half_sim: i32 = world.SIM_BUFFER_WIDTH / 2;
    const lo_x = @min(min_cx, -half_sim);
    const lo_y = @min(min_cy, -half_sim);
    const hi_x = @max(max_cx, half_sim - 1);
    const hi_y = @max(max_cy, half_sim - 1);

    preview_w = @intCast(hi_x - lo_x + 1);
    preview_h = @intCast(hi_y - lo_y + 1);
    preview_min = .{ lo_x, lo_y };
    preview_centre = .{ .suffix = transition.player_chunk, .quadrant = transition.player_quadrant };

    const needed = @as(usize, preview_w) * @as(usize, preview_h);
    if (preview.len != needed) {
        freeBuffers();
        preview = memory.main_allocator.alloc(Chunk, needed) catch memory.oom();
        preview_keys = memory.main_allocator.alloc(Coordinate, needed) catch memory.oom();
    }
    filled = 0;
}

/// Hands the preview allocations back, leaving the rest of the descent's state alone.
fn freeBuffers() void {
    if (preview.len != 0) memory.main_allocator.free(preview);
    if (preview_keys.len != 0) memory.main_allocator.free(preview_keys);
    preview = &.{};
    preview_keys = &.{};
}

/// Samples the block types around the player, then lays out the shards that will be swallowed.
///
/// Read-only with respect to the world: these are decorative copies, and no modification is written.
/// Everything is drawn from a seeded generator so a reload lays out the identical descent.
fn collectDebris() void {
    const g = &memory.game;

    // Sample the surrounding block types. Only the set of types matters; where each one sat does not,
    // since the shards are scattered on a ring rather than flown in from their real positions.
    var palette: [MAX_PALETTE]Sprite = undefined;
    var palette_len: usize = 0;

    const player_coord = g.getPlayerCoord();
    const player_bx: i32 = g.getBlockXInChunk();
    const player_by: i32 = g.getBlockYInChunk();

    var dy: i32 = -DEBRIS_RADIUS;
    while (dy < DEBRIS_RADIUS) : (dy += 1) {
        var dx: i32 = -DEBRIS_RADIUS;
        while (dx < DEBRIS_RADIUS) : (dx += 1) {
            const target_bx = player_bx + dx;
            const target_by = player_by + dy;
            const coord = player_coord.move(.{
                @divFloor(target_bx, dw.CHUNK_SIZE),
                @divFloor(target_by, dw.CHUNK_SIZE),
            }) orelse continue;
            const chunk = world.SimBuffer.get(coord) orelse continue;
            const block = chunk.getBlock(
                @intCast(@mod(target_bx, dw.CHUNK_SIZE)),
                @intCast(@mod(target_by, dw.CHUNK_SIZE)),
            );
            // Air has nothing to show, and the portal is the thing doing the swallowing.
            if (block.isEmpty() or block.id == .portal) continue;

            palette[palette_len] = block.id;
            palette_len += 1;
        }
    }
    // Standing in open air leaves nothing to swallow; the particles carry the effect alone.
    if (palette_len == 0) {
        clearDebris();
        return;
    }

    debris_count = SHARD_COUNT;

    var rng = dw.seeding.ChaCha12.init(&dw.seeding.mixBaseSeed(g.seed, .portal_debris));
    const span = SHARD_SPAWN_SPAN * @as(f64, @floatFromInt(TOTAL_FRAMES));

    for (&debris) |*shard| {
        // Square-rooting a uniform value biases the start times later, so the intake visibly builds
        // instead of arriving all at once.
        const when = @sqrt(rng.float(f64));
        shard.* = .{
            .sprite = palette[@intCast(rng.next() % palette_len)],
            .angle = @floatCast(rng.float(f64) * std.math.tau),
            .radius = SHARD_RADIUS_MIN + (SHARD_RADIUS_MAX - SHARD_RADIUS_MIN) * rng.float(f32),
            .size = SHARD_SIZE * (0.55 + 0.85 * rng.float(f32)),
            .spin = (rng.float(f32) - 0.5) * 6.0,
            .start_frame = @intFromFloat(when * span),
            .travel = SHARD_TRAVEL_MIN + @as(u32, @intCast(rng.next() % (SHARD_TRAVEL_MAX - SHARD_TRAVEL_MIN + 1))),
        };
    }
}

/// Drops every active shard. Nothing is freed: the array is fixed-size and lives with the module.
fn clearDebris() void {
    debris_count = 0;
}

/// Ceiling on the parent region handed to the ancestor cache, as a radius in D chunks.
/// 11x11 is already more than the hot tier holds (`AncestorCache.HOT_SIZE`),
/// so seeding past this would only evict what it just inserted.
const ANCESTOR_SEED_MAX_RADIUS: i64 = 5;

/// Radius in D chunks that covers every parent the preview will read.
///
/// Derived from the window rather than assumed: a zoomed-out camera can make the preview far wider than the `SimBuffer` window,
/// and a radius that fails to reach leaves exactly the cold ancestor walk this seeding exists to avoid.
/// Each D chunk covers `ZOOM_FACTOR` child chunks,
/// plus one for the generator's 6x6 block neighbourhood spilling into the next chunk over, plus one to round up.
fn ancestorSeedRadius() i64 {
    const far_x = @max(@abs(preview_min[0]), @abs(preview_min[0] + @as(i32, @intCast(preview_w)) - 1));
    const far_y = @max(@abs(preview_min[1]), @abs(preview_min[1] + @as(i32, @intCast(preview_h)) - 1));
    const reach = @divTrunc(@as(i64, @max(far_x, far_y)), dw.ZOOM_FACTOR) + 2;
    return @min(reach, ANCESTOR_SEED_MAX_RADIUS);
}

/// Copies the D chunks the preview reads as parents into the ancestor cache, keyed for the depth the preview generates at.
///
/// `AncestorCache` indexes tiers RELATIVE to `memory.game.depth` (see `relativeTier()`),
/// so installing the transition shifts every existing entry out of reach:
/// a parent at D lands on the tier that holds D-1, misses, and re-derives itself from D-1,
/// which misses in turn, all the way down the chain.
///
/// The `SimBuffer` already holds these chunks fully materialized, but `getCachedChunk()` only consults it when `key.depth == game.depth`,
/// which is false here. Copying them across turns every parent lookup into a hit,
/// so the preview never regenerates a chunk that is already in memory.
///
/// Precondition: the transition must already be installed, so `game.depth` is the preview's depth.
fn seedAncestorsFromSim(centre: Coordinate, parent_depth: u64) void {
    const radius = ancestorSeedRadius();
    var dy: i64 = -radius;
    while (dy <= radius) : (dy += 1) {
        var dx: i64 = -radius;
        while (dx <= radius) : (dx += 1) {
            const coord = centre.moveAtDepth(.{ dx, dy }, parent_depth) orelse continue;
            // Resident chunks only: anything absent would have to be generated either way.
            const chunk = world.SimBuffer.get(coord) orelse continue;
            _ = dw.ancestor.ancestor_cache.insert(coord.asDepthCoordinate(parent_depth), chunk.*);
        }
    }
}

/// Preview chunks to generate per frame. `CHUNKS_PER_FRAME` in the ordinary case,
/// raised only when a zoomed-out camera makes the window big enough that the baseline would miss `fill_deadline`.
inline fn chunksPerFrame() u32 {
    const total: u32 = @intCast(preview.len);
    return @max(CHUNKS_PER_FRAME, (total + fill_deadline - 1) / fill_deadline);
}

/// Generates the next `count` preview chunks.
///
/// Chunk generation reads the depth, quadrant seeds and rebase origins straight out of the globals,
/// so the D+1 transition is installed for the duration and taken back off afterwards.
/// The live D world is untouched: `restoreLayer()` is the exact inverse of `installLayer()`.
fn fillPreview(count: u32) void {
    if (filled >= preview.len) return;

    // Captured before the transition goes in, while these still describe D.
    const parent_coord = portalCoord();
    const parent_depth = memory.game.depth;

    const snapshot = world.snapshotLayer(transition.depth);
    world.installLayer(transition);
    defer world.restoreLayer(snapshot);

    // Descent-only: it warms the D parents the D+1 preview reads, which are resident in the SimBuffer.
    // An ascent reads D-2 parents (shallower than the live D world), which are not resident and would
    // key into a negative tier relative to the installed D-1 depth, so it is skipped entirely.
    if (filled == 0 and isDescending()) seedAncestorsFromSim(parent_coord, parent_depth);

    var made: u32 = 0;
    while (made < count and filled < preview.len) : ({
        made += 1;
        filled += 1;
    }) {
        const gx: i64 = @as(i64, preview_min[0]) + @as(i64, @intCast(filled % preview_w));
        const gy: i64 = @as(i64, preview_min[1]) + @as(i64, @intCast(filled / preview_w));
        const slot = &preview[filled];

        if (preview_centre.moveAtDepth(.{ gx, gy }, transition.depth)) |coord| {
            preview_keys[filled] = coord;
            world.materializeChunk(slot, coord.asDepthCoordinate(transition.depth));
        } else {
            // Past the world edge, matching how `updateVisibleChunks()` blanks the same case.
            // No real coordinate exists, so mark the slot unmatchable rather than leaving it undefined.
            preview_keys[filled] = .{ .suffix = .{ 0, 0 }, .quadrant = 0 };
            @memset(&slot.blocks, memory.Block.empty);
        }
    }
}

/// The generated D+1 chunk at `coord`, or null when it is outside the preview window or not yet made.
/// The overlay renders a null as empty space, which can only happen before the overlay is visible.
pub fn previewChunk(coord: Coordinate) ?*const Chunk {
    if (!ready or preview.len == 0) return null;

    // suffix subtraction wraps the same way `moveAtDepth()` does
    // the stored key then confirms it really is the right chunk!
    const dx = (coord.suffix[0] -% preview_centre.suffix[0]) -% @as(u64, @bitCast(@as(i64, preview_min[0])));
    const dy = (coord.suffix[1] -% preview_centre.suffix[1]) -% @as(u64, @bitCast(@as(i64, preview_min[1])));
    if (dx >= preview_w or dy >= preview_h) return null;

    const idx = dy * @as(u64, preview_w) + dx;
    if (idx >= filled) return null;
    if (!preview_keys[@intCast(idx)].eql(coord)) return null;
    return &preview[@intCast(idx)];
}

/// The overlay's transition (the depth being entered). Only valid while `isActive()`.
pub fn overlayTransition() world.LayerTransition {
    return transition;
}

/// Camera position for this frame, in subpixels relative to the player's chunk.
///
/// A descent eases the camera onto the portal as the player is drawn in, so the zoom closes on the
/// portal rather than on wherever the camera was loitering. An ascent locks onto the anchor (the
/// player's own point) from the first frame, so the pull-out is centred and nothing drifts.
/// `camera_pos` itself is never written, which is what lets this be recomputed from the frame counter
/// alone after a load.
pub fn cameraOverride() [2]f64 {
    const g = &memory.game;
    const t = if (isDescending()) smoothstep(pullProgress()) else 1.0;
    return .{
        @as(f64, @floatFromInt(g.camera_pos[0])) * (1.0 - t) + anchor[0] * t,
        @as(f64, @floatFromInt(g.camera_pos[1])) * (1.0 - t) + anchor[1] * t,
    };
}

/// Player position for this frame, in subpixels relative to the player's chunk.
/// Accelerates into the portal rather than easing out of it, so the pull reads as a grab.
pub fn playerOverride() [2]f64 {
    const g = &memory.game;
    const p = pullProgress();
    const t = p * p; // ease in: slow to give, then snatched
    return .{
        @as(f64, @floatFromInt(g.player_pos[0])) * (1.0 - t) + anchor[0] * t,
        @as(f64, @floatFromInt(g.player_pos[1])) * (1.0 - t) + anchor[1] * t,
    };
}

/// How much the player sprite is squeezed as the portal takes it.
///
/// Recovers to 1 by the last frame rather than staying small, so the commit has nothing to pop back from.
pub fn playerScale() f32 {
    if (!isActive()) return 1.0;
    const SQUEEZE = 0.55;
    // Undone in step with the zoom, so both arrive at their committed values on the same frame.
    return @floatCast(1.0 - SQUEEZE * smoothstep(pullProgress()) * (1.0 - zoomCurve(progress())));
}

/// Converts a world position (subpixels relative to the player's chunk) into viewport pixels,
/// using the same mapping the tile grid uses so effects stay locked to the blocks.
fn worldToScreen(sub: [2]f64) Vec2f32 {
    const zoom = memory.game.camera_scale * zoomFactor();
    const cam = cameraOverride();
    return .{
        @floatCast(@as(f64, dw.SCREEN_WIDTH_HALF) + (sub[0] - cam[0]) * zoom / dw.CHUNK_SIZE_FLOAT),
        @floatCast(@as(f64, dw.SCREEN_HEIGHT_HALF) + (sub[1] - cam[1]) * zoom / dw.CHUNK_SIZE_FLOAT),
    };
}

/// Draws the descent's effects: the terrain being swallowed.
/// Called once per render frame from `entity.updateEntities()`.
/// The intake particles are spawned from `tick()` instead, so their density does not ride the frame rate.
pub fn drawEffects() void {
    if (!isActive() or !ready) return;
    @setFloatMode(.optimized);
    drawDebris(worldToScreen(effect_centre));
}

/// Fade factor for portal-related visual elements (shards, particles) near the end of the descent.
pub fn getDescentFade() f32 {
    if (!isActive()) return 1.0;
    const t = progress();
    if (t < 0.8) return 1.0;
    return @floatCast((1.0 - t) / 0.2);
}

/// Draws each shard falling into the portal.
///
/// Purely screen-space: the ring, the sizes and the travel are all in viewport pixels,
/// so the zoom ramping to `ZOOM_FACTOR` underneath costs nothing here and the debris keeps arriving throughout.
fn drawDebris(centre: Vec2f32) void {
    const frame = memory.game.portal_frame;

    for (debris[0..debris_count]) |*shard| {
        if (frame < shard.start_frame) continue;
        const travelled: f64 = @floatFromInt(frame - shard.start_frame);
        const u = @min(travelled / @as(f64, @floatFromInt(shard.travel)), 1.0);
        if (u >= 1.0) continue; // already swallowed

        const eased: f32 = @floatCast(u * u);
        // Descent draws terrain inward to be swallowed; ascent throws it outward as the world opens up.
        const distance = shard.radius * (if (isDescending()) 1.0 - eased else eased);
        const pos: Vec2f32 = .{
            centre[0] + @cos(shard.angle) * distance,
            centre[1] + @sin(shard.angle) * distance,
        };

        // Fades up out of nothing, then fades out right as it enters the center.
        const appear = @min(eased * 6.0, 1.0);
        const alpha = appear * (1.0 - eased) * getDescentFade();

        dw.entity.addEntity(.{
            .sprite = shard.sprite,
            .position = pos,
            .size = shard.size * (1.0 - 0.75 * eased),
            .rotation = shard.spin * eased,
            .lcha = .{ 1.0, 0.0, 0.0, alpha },
        });
    }
}

/// Emits the portal's inward-falling particles, growing more insistent as the descent builds.
///
/// Deliberately outlives the intake fade: the particles are still going strong while the D+1 layer comes up underneath them,
/// which is what keeps that hand-over from reading as a dissolve.
/// They only thin out over the closing stretch, once the zoom alone carries the shot.
fn spawnIntake() void {
    @setFloatMode(.optimized);
    const t = progress();
    // Ramp in over the intake, hold through the overlay's arrival, then ease away at the very end.
    const ramp = smoothstep(@as(f64, @floatFromInt(memory.game.portal_frame)) / @as(f64, @floatFromInt(fill_deadline)));
    const TAIL_START = 0.8;
    const tail = if (t <= TAIL_START) 1.0 else 1.0 - smoothstep((t - TAIL_START) / (1.0 - TAIL_START));
    const intensity = ramp * tail;
    if (intensity <= 0.0) return;

    const zoom: f32 = @floatCast(memory.game.camera_scale * zoomFactor());
    // The pool holds thousands, so a descent this short can afford to be genuinely dense.
    const count: usize = @intFromFloat(5.0 + 55.0 * intensity);

    const cap: u16 = @intFromFloat(@round(22.0 - 22.0 * progress()));
    if (cap > 2) {
        dw.particles.spawnInwardRing(worldToScreen(effect_centre), &PORTAL_COLORS, .{
            .count = count,
            // Held in world scale so the ring hugs the portal as the view zooms.
            .radius_min = 10.0 * zoom,
            .radius_max = 26.0 * zoom,
            .size_min = 0.8 * zoom,
            .size_max = 2.6 * zoom,
            .travel_min = @min(cap, 8),
            .travel_max = cap,
            .swirl = @floatCast(0.25 + 0.5 * intensity),
            // A descent draws them in; an ascent pushes them out through the same ring.
            .outward = !isDescending(),
        });
    }
}

/// Advances the descent by one logical frame. Called once per tick iteration from `handleTick()`.
pub fn tick() void {
    if (!isActive()) return;
    ensureReady();

    const g = &memory.game;
    g.portal_frame +|= 1;

    if (g.portal_frame >= TOTAL_FRAMES) {
        finish();
        return;
    }

    fillPreview(chunksPerFrame());
    spawnIntake();

    // The world is frozen, so pinning the previous-frame values keeps render interpolation from drifting with nothing moving.
    // The descent's own motion is an override.
    g.camera_scale_change = 1.0;
    g.last_camera_pos = g.camera_pos;
    g.last_player_pos = g.player_pos;
}

/// Commits the descent so D+1 stops being a preview and becomes the world!
/// Adapts the preview buffer to the one-method interface `SimBuffer.refreshAdopting()` asks for.
const PreviewSource = struct {
    pub fn get(_: @This(), coord: Coordinate) ?*const Chunk {
        return previewChunk(coord);
    }
};

/// Adopts nothing, so `refreshAdopting()` regenerates every slot from scratch.
///
/// An ascent generated its D-1 preview BEFORE `applyAscent()` set the descendant markers, so those
/// chunks carry no markers. Regenerating them once the world is spectating rebakes the markers through
/// `materializeChunk()`. A descent never needs this: a chunk's `descendants` bitmap already encodes
/// exactly whether it has deeper edits, so adopting the preview is always correct there.
const EmptySource = struct {
    pub fn get(_: @This(), _: Coordinate) ?*const Chunk {
        return null;
    }
};

fn finish() void {
    const g = &memory.game;
    ensureReady();

    if (isDescending()) {
        // A descent while spectating is a retrace of the last ascent, so it pops that step.
        const retracing = world.isSpectating();
        // The preview left the ancestor cache holding this depth's parents, already tiered for it.
        world.commitLayer(transition, true);
        if (retracing) world.popAscentStep(
            g.getPlayerCoord(),
            @intCast(@divTrunc(transition.new_pos[0], dw.CHUNK_SIZE_SQ)),
            @intCast(@divTrunc(transition.new_pos[1], dw.CHUNK_SIZE_SQ)),
        );
    } else {
        // Records the retrace step and rolls the deeper depth's edits up into markers, then commits.
        world.applyAscent(transition);
    }

    // Hand the generated chunks to the SimBuffer before dropping them.
    // Skipping it does not avoid the work, only defers it: the next `player.move()` rebuilds all 256 slots in one frame,
    // and every render frame until then regenerates the visible window on top.
    world.SimBuffer.refreshAdopting(g.getPlayerCoord(), PreviewSource{});

    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();

    // The zoom multiplier drops back to 1 with the descent over,
    // and D+1 at the committed scale shows exactly what D showed at a full ZOOM_FACTOR!
    g.camera_scale_change = 1.0;
    dw.mining.selected_hp = 255;
    dw.mouse.mouse_chunk_coord = null;
}

/// Drops the preview buffer and forgets the derived state.
fn releasePreview() void {
    freeBuffers();
    clearDebris();
    preview_w = 0;
    preview_h = 0;
    filled = 0;
    ready = false;
}

/// Rebuilds everything a descent needs that a save does not carry, then brings the preview fully up to date in one go.
/// Called after a load; the frame counter alone decides what the player sees next.
pub fn restore() void {
    ready = false;
    if (!isActive()) {
        releasePreview();
        return;
    }
    ensureReady();
    // Loads can be slow!
    fillPreview(@intCast(preview.len));
}

/// Abandons any running descent and releases its memory. Used when a world is torn down.
pub fn reset() void {
    const g = &memory.game;
    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();
}
