//! The portal descent: the animation that carries the player from depth D down into D+1.
//!
//! A descent runs entirely on a frame counter (`memory.game.portal_frame`) advanced by `handleTick()`,
//! never on wall time, so it plays back identically at any frame rate and can be resumed from a save.
//! The committed world stays at D for every frame but the last;
//! D+1 is only ever a preview, generated into a scratch buffer and drawn over D as it fades in.
//!
//! Two phases:
//! - `.settle` eases the background wind to a standstill, drifts the camera onto the player,
//!   creeps the zoom out to `OVERLAY_ZOOM`, and fills the D+1 preview a few chunks at a time.
//! - `.zoom` drives the zoom the rest of the way to `ZOOM_FACTOR` while D+1 fades in over D.
//!   Reaching a full `ZOOM_FACTOR` means D+1 now covers exactly what D did, so committing there is seamless.
//!
//! Nothing here is stored beyond the handful of fields in `GameState`:
//! the transition and the preview buffer are both derived, and `restore()` rebuilds them after a load.
const std = @import("std");
const dw = @import("../root.zig");

const memory = dw.memory;
const world = dw.world;
const Chunk = memory.Chunk;
const Coordinate = world.Coordinate;

/// Frames spent settling before the zoom phase begins.
/// The zoom stays at or below `OVERLAY_ZOOM` for all of them, which is exactly the window
/// the D+1 preview is filled in, so the overlay is complete before it can ever be seen.
pub const SETTLE_FRAMES: u32 = 64;
/// Frames spent going from `OVERLAY_ZOOM` to a full `ZOOM_FACTOR` while D+1 fades in.
pub const ZOOM_FRAMES: u32 = 56;
/// Total length of a descent; at 60 logical ticks a second this is about two seconds.
pub const TOTAL_FRAMES: u32 = SETTLE_FRAMES + ZOOM_FRAMES;

/// Relative zoom the D+1 overlay starts becoming visible at.
/// The preview must be fully generated by the time the zoom reaches this.
pub const OVERLAY_ZOOM: f64 = 1.5;

/// Baseline number of preview chunks generated per settle frame.
/// The real rate (see `chunksPerFrame()`) only ever rises from here, so the buffer always
/// finishes filling within `SETTLE_FRAMES` no matter how far out the camera is zoomed.
pub const CHUNKS_PER_FRAME: u32 = 4;

comptime {
    // The preview is filled during the settle phase alone, so there must be a settle phase to fill it in.
    if (SETTLE_FRAMES == 0 or ZOOM_FRAMES == 0) @compileError("A descent needs both a settle and a zoom phase.");
    // The user-facing contract: the overlay may not become visible before the buffer is filled.
    if (SETTLE_FRAMES < 64) @compileError("At least 64 frames must pass before the zoom exceeds OVERLAY_ZOOM.");
    if (OVERLAY_ZOOM <= 1.0 or OVERLAY_ZOOM >= dw.ZOOM_FACTOR) @compileError("OVERLAY_ZOOM must sit between 1x and ZOOM_FACTOR.");
}

/// Which part of a descent is running. Stored in `GameState` as its integer tag.
pub const Phase = enum(u8) {
    idle,
    settle,
    zoom,
};

/// The D+1 transition, worked out once when the descent starts and reinstalled every frame
/// the preview is generated under. Valid only while `ready` is set.
var transition: world.LayerTransition = undefined;

/// D+1 chunks covering everything the overlay can show, taken from `main_allocator`.
/// Laid out as a `preview_w` by `preview_h` grid starting at `preview_origin`.
var preview: []Chunk = &.{};
/// The coordinate each `preview` slot holds, so a lookup can confirm it found the right chunk.
/// Needed because a window may straddle a quadrant boundary past the horizon,
/// where suffixes wrap and the quadrant flips; comparing suffix offsets alone would mismatch there.
var preview_keys: []Coordinate = &.{};
var preview_origin: Coordinate = undefined;
var preview_w: u32 = 0;
var preview_h: u32 = 0;

/// How many slots of `preview` hold generated chunks; the rest are still blank.
var filled: u32 = 0;

/// Whether `transition` and `preview` describe the descent `GameState` currently says is running.
/// Cleared by `reset()` and by a load, which is what makes `ensureReady()` rebuild them.
var ready: bool = false;

/// Whether a descent is currently playing.
pub inline fn isActive() bool {
    return phase() != .idle;
}

/// The running descent's phase.
pub inline fn phase() Phase {
    return switch (memory.game.portal_phase) {
        @intFromEnum(Phase.settle) => .settle,
        @intFromEnum(Phase.zoom) => .zoom,
        else => .idle,
    };
}

/// Smooth 0-1 ease with zero slope at both ends, so no phase boundary shows a velocity jump.
inline fn smoothstep(t: f64) f64 {
    const x = std.math.clamp(t, 0.0, 1.0);
    return x * x * (3.0 - 2.0 * x);
}

/// Progress through the settle phase, 0 at its first frame and 1 once the zoom phase starts.
inline fn settleProgress() f64 {
    const frame: f64 = @floatFromInt(@min(memory.game.portal_frame, SETTLE_FRAMES));
    return frame / @as(f64, @floatFromInt(SETTLE_FRAMES));
}

/// Progress through the zoom phase, 0 while settling and 1 on the committing frame.
inline fn zoomProgress() f64 {
    const frame = memory.game.portal_frame;
    if (frame <= SETTLE_FRAMES) return 0.0;
    const done: f64 = @floatFromInt(@min(frame - SETTLE_FRAMES, ZOOM_FRAMES));
    return done / @as(f64, @floatFromInt(ZOOM_FRAMES));
}

/// How much the world's zoom is multiplied by this frame: 1x at rest, easing to `OVERLAY_ZOOM`
/// across the settle phase and to a full `ZOOM_FACTOR` by the end of the zoom phase.
/// The D+1 overlay divides this by `ZOOM_FACTOR`, which is why reaching it lands exactly on the committed view.
pub fn zoomFactor() f64 {
    if (!isActive()) return 1.0;
    return switch (phase()) {
        .idle => 1.0,
        .settle => 1.0 + (OVERLAY_ZOOM - 1.0) * smoothstep(settleProgress()),
        .zoom => OVERLAY_ZOOM + (@as(f64, dw.ZOOM_FACTOR) - OVERLAY_ZOOM) * smoothstep(zoomProgress()),
    };
}

/// Opacity the D+1 layer (both its chunks and its background) is drawn at.
/// Stays at 0 until the zoom passes `OVERLAY_ZOOM`, then rises to fully cover D.
pub fn overlayOpacity() f64 {
    if (!isActive()) return 0.0;
    return smoothstep(zoomProgress());
}

/// Rate the background clock advances at, eased to a standstill across the settle phase
/// and held there for the rest of the descent.
pub fn backgroundRate() f64 {
    return switch (phase()) {
        .idle => 1.0,
        .settle => 1.0 - smoothstep(settleProgress()),
        .zoom => 0.0,
    };
}

/// Starts a descent through the portal at `coord`'s block (`bx`, `by`). Ignored if one is already running.
pub fn trigger(coord: Coordinate, bx: u4, by: u4) void {
    if (isActive()) return;

    const g = &memory.game;
    g.portal_chunk = coord.suffix;
    g.portal_quadrant = coord.quadrant;
    g.portal_bx = bx;
    g.portal_by = by;
    g.portal_frame = 0;
    g.portal_phase = @intFromEnum(Phase.settle);

    ready = false;
    ensureReady();
}

/// The portal that started the running descent, as recorded in `GameState`.
inline fn portalCoord() Coordinate {
    return .{
        .suffix = memory.game.portal_chunk,
        .quadrant = @intCast(memory.game.portal_quadrant & 3),
    };
}

/// Works out the D+1 transition and sizes the preview buffer for the running descent.
/// Safe to call repeatedly; only the first call after a trigger (or a load) does any work.
fn ensureReady() void {
    if (ready or !isActive()) return;

    transition = world.computeLayer(
        portalCoord(),
        @intCast(memory.game.portal_bx & 15),
        @intCast(memory.game.portal_by & 15),
    );
    allocatePreview();
    ready = true;
}

/// Sizes and clears the D+1 preview to cover the widest view the overlay can ever show.
///
/// That widest view is the instant the overlay appears, at `OVERLAY_ZOOM`: the D+1 layer is drawn at
/// `zoomFactor() / ZOOM_FACTOR`, which only grows from there, so the footprint only ever shrinks.
fn allocatePreview() void {
    const g = &memory.game;
    // The zoom the D+1 layer is drawn at when it first becomes visible (its most zoomed-out state).
    const widest_zoom = g.camera_scale * OVERLAY_ZOOM / @as(f64, dw.ZOOM_FACTOR);

    const subpixels_per_chunk: f64 = @floatFromInt(dw.SUBPIXELS_IN_CHUNK);
    const half_w_sp = (@as(f64, dw.SCREEN_WIDTH_HALF) / widest_zoom) * dw.CHUNK_SIZE;
    const half_h_sp = (@as(f64, dw.SCREEN_HEIGHT_HALF) / widest_zoom) * dw.CHUNK_SIZE;

    // The camera has been drawn onto the player by the time the overlay shows, so the D+1 view is
    // centred on where the player lands, which is exactly what the transition computed.
    const cam_x: f64 = @floatFromInt(transition.new_pos[0]);
    const cam_y: f64 = @floatFromInt(transition.new_pos[1]);

    const margin: i32 = @intCast(dw.lighting.CHUNK_MARGIN);
    const min_cx = @as(i32, @intFromFloat(@floor((cam_x - half_w_sp) / subpixels_per_chunk))) - margin;
    const min_cy = @as(i32, @intFromFloat(@floor((cam_y - half_h_sp) / subpixels_per_chunk))) - margin;
    const max_cx = @as(i32, @intFromFloat(@floor((cam_x + half_w_sp) / subpixels_per_chunk))) + margin;
    const max_cy = @as(i32, @intFromFloat(@floor((cam_y + half_h_sp) / subpixels_per_chunk))) + margin;

    preview_w = @intCast(max_cx - min_cx + 1);
    preview_h = @intCast(max_cy - min_cy + 1);

    // The origin can fall off the world at an edge; clamping it would misalign the whole grid, so the
    // grid keeps its position and out-of-world cells simply stay blank (see fillPreview()).
    const centre: Coordinate = .{ .suffix = transition.player_chunk, .quadrant = transition.player_quadrant };
    preview_origin = centre.moveAtDepth(.{ min_cx, min_cy }, transition.depth) orelse centre;

    const needed = @as(usize, preview_w) * @as(usize, preview_h);
    if (preview.len != needed) {
        freeBuffers();
        preview = memory.main_allocator.alloc(Chunk, needed) catch memory.oom();
        preview_keys = memory.main_allocator.alloc(Coordinate, needed) catch memory.oom();
    }
    filled = 0;
}

/// Hands the preview allocations back, leaving the rest of the descent's state alone.
fn freeBuffers() void {
    if (preview.len != 0) memory.main_allocator.free(preview);
    if (preview_keys.len != 0) memory.main_allocator.free(preview_keys);
    preview = &.{};
    preview_keys = &.{};
}

/// Preview chunks to generate per settle frame. `CHUNKS_PER_FRAME` in the ordinary case, raised only
/// when a zoomed-out camera makes the window big enough that the baseline would not finish in time.
inline fn chunksPerFrame() u32 {
    const total: u32 = @intCast(preview.len);
    return @max(CHUNKS_PER_FRAME, (total + SETTLE_FRAMES - 1) / SETTLE_FRAMES);
}

/// Generates the next `count` preview chunks.
///
/// Chunk generation reads the depth, quadrant seeds and rebase origins straight out of the globals,
/// so the D+1 transition is installed for the duration and taken back off afterwards.
/// The live D world is untouched: `restoreLayer()` is the exact inverse of `installLayer()`.
fn fillPreview(count: u32) void {
    if (filled >= preview.len) return;

    const snapshot = world.snapshotLayer(transition.depth);
    world.installLayer(transition);
    defer world.restoreLayer(snapshot);

    var made: u32 = 0;
    while (made < count and filled < preview.len) : ({
        made += 1;
        filled += 1;
    }) {
        const gx: i64 = @intCast(filled % preview_w);
        const gy: i64 = @intCast(filled / preview_w);
        const slot = &preview[filled];

        if (preview_origin.moveAtDepth(.{ gx, gy }, transition.depth)) |coord| {
            preview_keys[filled] = coord;
            world.materializeChunk(slot, coord.asDepthCoordinate(transition.depth));
        } else {
            // Past the world edge, matching how `updateVisibleChunks()` blanks the same case.
            // No real coordinate exists, so mark the slot unmatchable rather than leaving it undefined.
            preview_keys[filled] = .{ .suffix = .{ 0, 0 }, .quadrant = 0 };
            @memset(&slot.blocks, memory.Block.empty);
        }
    }
}

/// The generated D+1 chunk at `coord`, or null when it is outside the preview window or not yet made.
/// The overlay renders a null as empty space, which can only happen before the overlay is visible.
pub fn previewChunk(coord: Coordinate) ?*const Chunk {
    if (!ready or preview.len == 0) return null;

    // Suffix subtraction wraps the same way `moveAtDepth()` does, so this locates the slot even when the
    // window straddles a quadrant boundary; the stored key then confirms it really is the right chunk.
    const dx = coord.suffix[0] -% preview_origin.suffix[0];
    const dy = coord.suffix[1] -% preview_origin.suffix[1];
    if (dx >= preview_w or dy >= preview_h) return null;

    const idx = dy * @as(u64, preview_w) + dx;
    if (idx >= filled) return null;
    if (!preview_keys[@intCast(idx)].eql(coord)) return null;
    return &preview[@intCast(idx)];
}

/// The D+1 transition the overlay renders against. Only valid while `isActive()`.
pub fn overlayTransition() world.LayerTransition {
    return transition;
}

/// Advances the descent by one logical frame. Called once per tick iteration from `handleTick()`.
pub fn tick() void {
    if (!isActive()) return;
    ensureReady();

    const g = &memory.game;
    g.portal_frame +|= 1;

    if (g.portal_frame >= TOTAL_FRAMES) {
        finish();
        return;
    }

    if (g.portal_frame <= SETTLE_FRAMES) {
        g.portal_phase = @intFromEnum(Phase.settle);
        fillPreview(chunksPerFrame());
        drawCameraOntoPlayer();
    } else {
        g.portal_phase = @intFromEnum(Phase.zoom);
        // The camera is already locked onto the player; hold it there for the rest of the descent.
        g.camera_pos = g.player_pos;
    }

    // The world is frozen, so pinning the previous-frame values keeps render interpolation from
    // drifting the view while nothing is actually moving.
    g.camera_scale_change = 1.0;
    g.last_camera_pos = g.camera_pos;
    g.last_player_pos = g.player_pos;
}

/// Eases the camera onto the player so that, once the zoom phase begins, the view is centred exactly
/// where the transition drops the player. Without this the commit would visibly jump by the camera's lag.
fn drawCameraOntoPlayer() void {
    const g = &memory.game;
    if (g.portal_frame >= SETTLE_FRAMES) {
        g.camera_pos = g.player_pos; // land exactly on it rather than merely close
        return;
    }

    // Closing a fixed fraction of what is left each frame: resume-safe, since it needs no memory of
    // where the camera started, and it lands exactly on the player as `remaining` reaches 1.
    const remaining: i64 = @intCast(SETTLE_FRAMES - g.portal_frame);
    inline for (0..2) |axis| {
        const delta = g.player_pos[axis] - g.camera_pos[axis];
        const step = @divTrunc(delta, remaining);
        // Truncation would stall the last few subpixels, so always creep by at least one.
        g.camera_pos[axis] += if (step == 0) std.math.sign(delta) else step;
    }
}

/// Commits the descent: D+1 stops being a preview and becomes the world.
fn finish() void {
    const g = &memory.game;
    ensureReady();
    world.commitLayer(transition);

    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();

    // The zoom multiplier drops back to 1 with the descent over, and D+1 at the committed scale shows
    // exactly what D showed at a full ZOOM_FACTOR, so the view carries straight through.
    g.camera_scale_change = 1.0;
    dw.mining.selected_hp = 255;
    dw.mouse.mouse_chunk_coord = null;
}

/// Drops the preview buffer and forgets the derived state.
fn releasePreview() void {
    freeBuffers();
    preview_w = 0;
    preview_h = 0;
    filled = 0;
    ready = false;
}

/// Rebuilds everything a descent needs that a save does not carry, then brings the preview fully up to
/// date in one go. Called after a load; the frame counter alone decides what the player sees next.
pub fn restore() void {
    ready = false;
    if (!isActive()) {
        releasePreview();
        return;
    }
    ensureReady();
    // A load is allowed to be slow, so the buffer is filled outright rather than over the frames that
    // would ordinarily have done it (those frames are already in the past).
    fillPreview(@intCast(preview.len));
}

/// Abandons any running descent and releases its memory. Used when a world is torn down.
pub fn reset() void {
    const g = &memory.game;
    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();
}
