//! The portal descent: the animation that carries the player from depth D down into D+1.
//!
//! A descent runs entirely on a frame counter (`memory.game.portal_frame`) advanced by `handleTick()`,
//! never on wall time, so it plays back identically at any frame rate and can be resumed from a save.
//! The committed world stays at D for every frame but the last;
//! D+1 is only ever a preview, generated into a scratch buffer and drawn over D as it fades in.
//!
//! There are deliberately no phases. One continuous zoom curve runs the whole descent, and everything
//! else (the intake particles, the debris being swallowed, the player being drawn in, the background
//! easing to a standstill) is a function of that same progress,
//! so nothing reads as a seam between one stage and the next.
//!
//! Nothing here is stored beyond the handful of fields in `GameState`:
//! the transition, the preview buffer and the debris are all derived, and `restore()` rebuilds them
//! after a load. In particular the player and camera are never actually moved during a descent;
//! their motion is an override applied at render time (see `cameraOverride()`), which keeps
//! `player_pos`'s "inside the current chunk" invariant intact and keeps the whole thing resumable.
const std = @import("std");
const dw = @import("../root.zig");

const memory = dw.memory;
const world = dw.world;
const Chunk = memory.Chunk;
const Sprite = dw.Sprite;
const Coordinate = world.Coordinate;
const Vec2f32 = dw.utils.Vec2f32;

/// Length of a descent; at 60 logical ticks a second this is a bit over two seconds.
pub const TOTAL_FRAMES: u32 = 140;
/// Frames the player takes to be drawn from where they stand into the portal's mouth.
pub const PULL_FRAMES: u32 = 40;

/// Relative zoom the D+1 overlay starts becoming visible at.
/// The preview must be fully generated by the time the zoom reaches this.
pub const OVERLAY_ZOOM: f64 = 1.5;

/// Baseline number of preview chunks generated per frame.
/// The real rate (see `chunksPerFrame()`) only ever rises from here, so the buffer always finishes
/// filling before the overlay can be seen, no matter how far out the camera is zoomed.
pub const CHUNKS_PER_FRAME: u32 = 4;

/// Frames the zoom must stay at or below `OVERLAY_ZOOM` for, giving the preview time to fill.
/// Asserted against the actual curve at the start of every descent rather than assumed.
pub const MIN_FILL_FRAMES: u32 = 64;

/// Half-width of the block window whose contents are swallowed, in blocks (so an 8x8 window).
pub const DEBRIS_RADIUS: i32 = 4;
/// Upper bound on swallowed blocks, which is the whole window.
const MAX_DEBRIS: usize = @intCast(4 * DEBRIS_RADIUS * DEBRIS_RADIUS);

/// Frames one piece of debris takes to reach the portal once it starts moving.
const DEBRIS_TRAVEL: u32 = 30;

/// Blue-cyan tints for the intake particles. `.particle` is a white sprite, so chroma and hue here are
/// added straight onto it (see `DEFAULT_ENTITY_LCHA`); hue is in radians.
const PORTAL_COLORS = [_][4]f32{
    .{ 0.85, 0.16, 4.55, 1.0 },
    .{ 0.95, 0.13, 4.75, 1.0 },
    .{ 0.75, 0.19, 4.35, 1.0 },
    .{ 1.00, 0.10, 4.95, 1.0 },
};

comptime {
    if (PULL_FRAMES >= TOTAL_FRAMES) @compileError("The player must finish being drawn in before the descent lands.");
    if (OVERLAY_ZOOM <= 1.0 or OVERLAY_ZOOM >= dw.ZOOM_FACTOR) @compileError("OVERLAY_ZOOM must sit between 1x and ZOOM_FACTOR.");
}

/// Which part of a descent is running. Stored in `GameState` as its integer tag.
pub const Phase = enum(u8) {
    idle,
    /// The one and only running state; the descent is shaped by `portal_frame`, not by phase.
    descending,
};

/// One block being swallowed: a purely visual echo of terrain near the player.
/// The world itself is never touched, so no modification is ever written for this.
const DebrisMote = struct {
    sprite: Sprite,
    /// Where it starts, in subpixels relative to the player's chunk.
    start: [2]f64,
    /// Frame it begins moving. Staggered by distance, so the pull appears to spread outward.
    start_frame: u32,
};

/// The D+1 transition, worked out once when the descent starts and reinstalled every frame
/// the preview is generated under. Valid only while `ready` is set.
var transition: world.LayerTransition = undefined;

/// D+1 chunks covering everything the overlay can show, taken from `main_allocator`.
var preview: []Chunk = &.{};
/// The coordinate each `preview` slot holds, so a lookup can confirm it found the right chunk.
/// Needed because a window may straddle a quadrant boundary past the horizon,
/// where suffixes wrap and the quadrant flips; comparing suffix offsets alone would mismatch there.
var preview_keys: []Coordinate = &.{};

/// Chunk the grid is measured out from: where the player lands at D+1.
/// The grid is anchored here rather than on its own top-left corner, since that corner can fall off
/// the world (near an edge) and have no coordinate at all to anchor to.
var preview_centre: Coordinate = undefined;
/// Chunk offset of the grid's top-left cell from `preview_centre`.
var preview_min: [2]i32 = .{ 0, 0 };
var preview_w: u32 = 0;
var preview_h: u32 = 0;

/// How many slots of `preview` hold generated chunks; the rest are still blank.
var filled: u32 = 0;
/// Frame by which the preview must be complete, derived from where the zoom curve crosses `OVERLAY_ZOOM`.
var fill_deadline: u32 = MIN_FILL_FRAMES;

/// The point everything converges on, in subpixels relative to the player's chunk: the spot inside the
/// portal block that maps exactly onto where the player lands at D+1. Zooming into it and then
/// committing therefore lands on the very same world point, with nothing to jump.
var anchor: [2]f64 = .{ 0.0, 0.0 };

var debris: [MAX_DEBRIS]DebrisMote = undefined;
var debris_count: u32 = 0;

/// Whether `transition`, `preview`, `anchor` and `debris` describe the descent `GameState` says is running.
/// Cleared by `reset()` and by a load, which is what makes `ensureReady()` rebuild them.
var ready: bool = false;

/// Whether a descent is currently playing.
pub inline fn isActive() bool {
    return memory.game.portal_phase == @intFromEnum(Phase.descending);
}

/// Smooth 0-1 ease with zero slope at both ends.
inline fn smoothstep(t: f64) f64 {
    const x = std.math.clamp(t, 0.0, 1.0);
    return x * x * (3.0 - 2.0 * x);
}

/// How far through the descent we are, 0 at the first frame and 1 on the committing frame.
inline fn progress() f64 {
    return @as(f64, @floatFromInt(memory.game.portal_frame)) / @as(f64, @floatFromInt(TOTAL_FRAMES));
}

/// Exponent of the zoom at progress `t`, where the zoom is `ZOOM_FACTOR` raised to it.
///
/// Driving an exponent (rather than the zoom itself) makes each frame scale the view by a near-constant
/// ratio, which is what reads as a steady, linear-feeling zoom instead of one that lurches at the end.
/// Squaring the smoothstep keeps the slope at zero on both ends (so it eases in and out) while holding
/// the early frames low enough for the preview to finish generating before the overlay appears.
inline fn zoomCurve(t: f64) f64 {
    const s = smoothstep(t);
    return s * s;
}

/// How much the world's zoom is multiplied by this frame: 1x at rest, `ZOOM_FACTOR` on the last frame.
/// The D+1 overlay divides this by `ZOOM_FACTOR`, which is why reaching it lands exactly on the committed view.
pub fn zoomFactor() f64 {
    if (!isActive()) return 1.0;
    return std.math.pow(f64, @as(f64, dw.ZOOM_FACTOR), zoomCurve(progress()));
}

/// The zoom multiplier at an arbitrary frame, for planning ahead of time.
fn zoomFactorAt(frame: u32) f64 {
    const t = @as(f64, @floatFromInt(frame)) / @as(f64, @floatFromInt(TOTAL_FRAMES));
    return std.math.pow(f64, @as(f64, dw.ZOOM_FACTOR), zoomCurve(t));
}

/// Opacity the D+1 layer (chunks and background alike) is drawn at.
///
/// Tied to the same curve as the zoom rather than to a stage of its own, so the hand-over from D to
/// D+1 rides the zoom instead of reading as a dissolve laid over it.
pub fn overlayOpacity() f64 {
    if (!isActive()) return 0.0;
    const start = zoomCurve(@as(f64, @floatFromInt(fill_deadline)) / @as(f64, @floatFromInt(TOTAL_FRAMES)));
    const now = zoomCurve(progress());
    if (now <= start) return 0.0;
    return smoothstep((now - start) / (1.0 - start));
}

/// How far the player has been drawn into the portal, 0 to 1.
inline fn pullProgress() f64 {
    const frame: f64 = @floatFromInt(@min(memory.game.portal_frame, PULL_FRAMES));
    return frame / @as(f64, @floatFromInt(PULL_FRAMES));
}

/// Fade applied to everything drawn in world space during the intake (debris, and the player itself).
/// Reaches 0 by the time the overlay appears, which spares every one of them from having to be
/// rescaled against a zoom that is about to quadruple.
pub fn intakeFade() f32 {
    if (!isActive()) return 1.0;
    const done = @as(f64, @floatFromInt(memory.game.portal_frame)) / @as(f64, @floatFromInt(fill_deadline));
    return @floatCast(1.0 - smoothstep(done));
}

/// Rate the background clock advances at, eased to a standstill as the player is drawn in.
pub fn backgroundRate() f64 {
    if (!isActive()) return 1.0;
    return 1.0 - smoothstep(pullProgress());
}

/// Starts a descent through the portal at `coord`'s block (`bx`, `by`). Ignored if one is already running.
pub fn trigger(coord: Coordinate, bx: u4, by: u4) void {
    if (isActive()) return;

    const g = &memory.game;
    g.portal_chunk = coord.suffix;
    g.portal_quadrant = coord.quadrant;
    g.portal_bx = bx;
    g.portal_by = by;
    g.portal_frame = 0;
    g.portal_phase = @intFromEnum(Phase.descending);

    ready = false;
    ensureReady();
}

/// The portal that started the running descent, as recorded in `GameState`.
inline fn portalCoord() Coordinate {
    return .{
        .suffix = memory.game.portal_chunk,
        .quadrant = @intCast(memory.game.portal_quadrant & 3),
    };
}

/// Works out everything a descent needs that a save does not carry.
/// Safe to call repeatedly; only the first call after a trigger (or a load) does any work.
fn ensureReady() void {
    if (ready or !isActive()) return;

    const bx: u4 = @intCast(memory.game.portal_bx & 15);
    const by: u4 = @intCast(memory.game.portal_by & 15);

    // `.block_floor` pins the landing to the portal block itself. Deriving it from the player instead
    // would place them wherever they happened to be standing scaled up, which need not even be inside
    // the portal, and can land inside solid terrain.
    transition = world.computeLayer(portalCoord(), bx, by, .block_floor);

    computeAnchor(bx, by);
    planFill();
    allocatePreview();
    collectDebris();
    ready = true;
}

/// Locates the D-space point matching where the player lands at D+1.
///
/// The landing sits at some offset inside the portal block's child region; dividing that offset by
/// `ZOOM_FACTOR` gives the same spot expressed in the parent block, which is what the camera has to
/// arrive at for the commit to be seamless.
fn computeAnchor(bx: u4, by: u4) void {
    const g = &memory.game;
    const player_coord = g.getPlayerCoord();
    const portal = portalCoord();

    // Wrapping subtraction gives the signed chunk delta, matching how `moveAtDepth()` steps.
    const chunk_dx: i64 = @bitCast(portal.suffix[0] -% player_coord.suffix[0]);
    const chunk_dy: i64 = @bitCast(portal.suffix[1] -% player_coord.suffix[1]);

    // Offset of the landing within its child region, brought back into parent-block scale.
    // Read off the transition rather than restated here, so the two can never disagree about where
    // the descent actually puts the player.
    const region: i64 = dw.CHUNK_SIZE_SQ * dw.ZOOM_FACTOR;
    const in_region_x: f64 = @floatFromInt(@mod(transition.new_pos[0], region));
    const in_region_y: f64 = @floatFromInt(@mod(transition.new_pos[1], region));

    const block: f64 = @floatFromInt(dw.CHUNK_SIZE_SQ);
    anchor = .{
        @as(f64, @floatFromInt(chunk_dx * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(bx)) * block + in_region_x / dw.ZOOM_FACTOR,
        @as(f64, @floatFromInt(chunk_dy * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(by)) * block + in_region_y / dw.ZOOM_FACTOR,
    };
}

/// Finds the last frame the zoom is still at or below `OVERLAY_ZOOM`, which is the deadline the
/// preview has to be complete by. Derived from the curve rather than hard-coded, so retuning the
/// timing cannot silently let the overlay appear over half-generated chunks.
fn planFill() void {
    fill_deadline = TOTAL_FRAMES;
    var frame: u32 = 0;
    while (frame <= TOTAL_FRAMES) : (frame += 1) {
        if (zoomFactorAt(frame) > OVERLAY_ZOOM) {
            fill_deadline = frame;
            break;
        }
    }
    std.debug.assert(fill_deadline >= MIN_FILL_FRAMES);
}

/// Sizes and clears the D+1 preview to cover the widest view the overlay can ever show.
///
/// That widest view is the instant the overlay appears, at `OVERLAY_ZOOM`: the D+1 layer is drawn at
/// `zoomFactor() / ZOOM_FACTOR`, which only grows from there, so the footprint only ever shrinks.
fn allocatePreview() void {
    const g = &memory.game;
    // The zoom the D+1 layer is drawn at when it first becomes visible (its most zoomed-out state).
    const widest_zoom = g.camera_scale * OVERLAY_ZOOM / @as(f64, dw.ZOOM_FACTOR);

    const subpixels_per_chunk: f64 = @floatFromInt(dw.SUBPIXELS_IN_CHUNK);
    const half_w_sp = (@as(f64, dw.SCREEN_WIDTH_HALF) / widest_zoom) * dw.CHUNK_SIZE;
    const half_h_sp = (@as(f64, dw.SCREEN_HEIGHT_HALF) / widest_zoom) * dw.CHUNK_SIZE;

    // The camera has arrived on the landing point by the time the overlay shows, so the D+1 view is
    // centred on exactly what the transition computed.
    const cam_x: f64 = @floatFromInt(transition.new_pos[0]);
    const cam_y: f64 = @floatFromInt(transition.new_pos[1]);

    const margin: i32 = @intCast(dw.lighting.CHUNK_MARGIN);
    const min_cx = @as(i32, @intFromFloat(@floor((cam_x - half_w_sp) / subpixels_per_chunk))) - margin;
    const min_cy = @as(i32, @intFromFloat(@floor((cam_y - half_h_sp) / subpixels_per_chunk))) - margin;
    const max_cx = @as(i32, @intFromFloat(@floor((cam_x + half_w_sp) / subpixels_per_chunk))) + margin;
    const max_cy = @as(i32, @intFromFloat(@floor((cam_y + half_h_sp) / subpixels_per_chunk))) + margin;

    preview_w = @intCast(max_cx - min_cx + 1);
    preview_h = @intCast(max_cy - min_cy + 1);
    preview_min = .{ min_cx, min_cy };
    preview_centre = .{ .suffix = transition.player_chunk, .quadrant = transition.player_quadrant };

    const needed = @as(usize, preview_w) * @as(usize, preview_h);
    if (preview.len != needed) {
        freeBuffers();
        preview = memory.main_allocator.alloc(Chunk, needed) catch memory.oom();
        preview_keys = memory.main_allocator.alloc(Coordinate, needed) catch memory.oom();
    }
    filled = 0;
}

/// Hands the preview allocations back, leaving the rest of the descent's state alone.
fn freeBuffers() void {
    if (preview.len != 0) memory.main_allocator.free(preview);
    if (preview_keys.len != 0) memory.main_allocator.free(preview_keys);
    preview = &.{};
    preview_keys = &.{};
}

/// Snapshots the terrain around the player so it can be shown spiralling into the portal.
/// Read-only: these are decorative copies, and the blocks themselves are left exactly as they are.
fn collectDebris() void {
    debris_count = 0;

    const g = &memory.game;
    const player_coord = g.getPlayerCoord();
    const player_bx: i32 = g.getBlockXInChunk();
    const player_by: i32 = g.getBlockYInChunk();
    // Distance at which a mote starts last, used to spread the pull outward from the portal.
    const furthest: f64 = @sqrt(@as(f64, @floatFromInt(2 * DEBRIS_RADIUS * DEBRIS_RADIUS)));

    var dy: i32 = -DEBRIS_RADIUS;
    while (dy < DEBRIS_RADIUS) : (dy += 1) {
        var dx: i32 = -DEBRIS_RADIUS;
        while (dx < DEBRIS_RADIUS) : (dx += 1) {
            if (debris_count >= MAX_DEBRIS) return;

            const target_bx = player_bx + dx;
            const target_by = player_by + dy;
            const chunk_dx = @divFloor(target_bx, dw.CHUNK_SIZE);
            const chunk_dy = @divFloor(target_by, dw.CHUNK_SIZE);
            const local_bx: u4 = @intCast(@mod(target_bx, dw.CHUNK_SIZE));
            const local_by: u4 = @intCast(@mod(target_by, dw.CHUNK_SIZE));

            const coord = player_coord.move(.{ chunk_dx, chunk_dy }) orelse continue;
            const chunk = world.SimBuffer.get(coord) orelse continue;
            const block = chunk.getBlock(local_bx, local_by);
            // Air has nothing to show, and the portal is the thing doing the swallowing.
            if (block.isEmpty() or block.id == .portal) continue;

            const distance = @sqrt(@as(f64, @floatFromInt(dx * dx + dy * dy)));
            const block_sp: f64 = @floatFromInt(dw.CHUNK_SIZE_SQ);
            debris[debris_count] = .{
                .sprite = block.id,
                .start = .{
                    @as(f64, @floatFromInt(chunk_dx * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(local_bx)) * block_sp + block_sp / 2.0,
                    @as(f64, @floatFromInt(chunk_dy * dw.SUBPIXELS_IN_CHUNK)) + @as(f64, @floatFromInt(local_by)) * block_sp + block_sp / 2.0,
                },
                // Nearer blocks go first, so the portal's reach visibly widens as the descent builds.
                .start_frame = @intFromFloat((distance / furthest) * @as(f64, @floatFromInt(PULL_FRAMES))),
            };
            debris_count += 1;
        }
    }
}

/// Preview chunks to generate per frame. `CHUNKS_PER_FRAME` in the ordinary case, raised only when a
/// zoomed-out camera makes the window big enough that the baseline would miss `fill_deadline`.
inline fn chunksPerFrame() u32 {
    const total: u32 = @intCast(preview.len);
    return @max(CHUNKS_PER_FRAME, (total + fill_deadline - 1) / fill_deadline);
}

/// Generates the next `count` preview chunks.
///
/// Chunk generation reads the depth, quadrant seeds and rebase origins straight out of the globals,
/// so the D+1 transition is installed for the duration and taken back off afterwards.
/// The live D world is untouched: `restoreLayer()` is the exact inverse of `installLayer()`.
fn fillPreview(count: u32) void {
    if (filled >= preview.len) return;

    const snapshot = world.snapshotLayer(transition.depth);
    world.installLayer(transition);
    defer world.restoreLayer(snapshot);

    var made: u32 = 0;
    while (made < count and filled < preview.len) : ({
        made += 1;
        filled += 1;
    }) {
        const gx: i64 = @as(i64, preview_min[0]) + @as(i64, @intCast(filled % preview_w));
        const gy: i64 = @as(i64, preview_min[1]) + @as(i64, @intCast(filled / preview_w));
        const slot = &preview[filled];

        if (preview_centre.moveAtDepth(.{ gx, gy }, transition.depth)) |coord| {
            preview_keys[filled] = coord;
            world.materializeChunk(slot, coord.asDepthCoordinate(transition.depth));
        } else {
            // Past the world edge, matching how `updateVisibleChunks()` blanks the same case.
            // No real coordinate exists, so mark the slot unmatchable rather than leaving it undefined.
            preview_keys[filled] = .{ .suffix = .{ 0, 0 }, .quadrant = 0 };
            @memset(&slot.blocks, memory.Block.empty);
        }
    }
}

/// The generated D+1 chunk at `coord`, or null when it is outside the preview window or not yet made.
/// The overlay renders a null as empty space, which can only happen before the overlay is visible.
pub fn previewChunk(coord: Coordinate) ?*const Chunk {
    if (!ready or preview.len == 0) return null;

    // Suffix subtraction wraps the same way `moveAtDepth()` does, so this locates the slot even when the
    // window straddles a quadrant boundary; the stored key then confirms it really is the right chunk.
    const dx = (coord.suffix[0] -% preview_centre.suffix[0]) -% @as(u64, @bitCast(@as(i64, preview_min[0])));
    const dy = (coord.suffix[1] -% preview_centre.suffix[1]) -% @as(u64, @bitCast(@as(i64, preview_min[1])));
    if (dx >= preview_w or dy >= preview_h) return null;

    const idx = dy * @as(u64, preview_w) + dx;
    if (idx >= filled) return null;
    if (!preview_keys[@intCast(idx)].eql(coord)) return null;
    return &preview[@intCast(idx)];
}

/// The D+1 transition the overlay renders against. Only valid while `isActive()`.
pub fn overlayTransition() world.LayerTransition {
    return transition;
}

/// Camera position for this frame, in subpixels relative to the player's chunk.
///
/// Eased onto the anchor as the player is drawn in, so the zoom closes on the portal rather than on
/// wherever the camera was loitering. `camera_pos` itself is never written, which is what lets this be
/// recomputed from the frame counter alone after a load.
pub fn cameraOverride() [2]f64 {
    const g = &memory.game;
    const t = smoothstep(pullProgress());
    return .{
        @as(f64, @floatFromInt(g.camera_pos[0])) * (1.0 - t) + anchor[0] * t,
        @as(f64, @floatFromInt(g.camera_pos[1])) * (1.0 - t) + anchor[1] * t,
    };
}

/// Player position for this frame, in subpixels relative to the player's chunk.
/// Accelerates into the portal rather than easing out of it, so the pull reads as a grab.
pub fn playerOverride() [2]f64 {
    const g = &memory.game;
    const p = pullProgress();
    const t = p * p; // ease in: slow to give, then snatched
    return .{
        @as(f64, @floatFromInt(g.player_pos[0])) * (1.0 - t) + anchor[0] * t,
        @as(f64, @floatFromInt(g.player_pos[1])) * (1.0 - t) + anchor[1] * t,
    };
}

/// How much the player sprite shrinks as it is swallowed.
pub fn playerScale() f32 {
    if (!isActive()) return 1.0;
    return @floatCast(1.0 - 0.55 * smoothstep(pullProgress()));
}

/// Converts a world position (subpixels relative to the player's chunk) into viewport pixels,
/// using the same mapping the tile grid uses so effects stay locked to the blocks.
fn worldToScreen(sub: [2]f64) Vec2f32 {
    const zoom = memory.game.camera_scale * zoomFactor();
    const cam = cameraOverride();
    return .{
        @floatCast(@as(f64, dw.SCREEN_WIDTH_HALF) + (sub[0] - cam[0]) * zoom / dw.CHUNK_SIZE_FLOAT),
        @floatCast(@as(f64, dw.SCREEN_HEIGHT_HALF) + (sub[1] - cam[1]) * zoom / dw.CHUNK_SIZE_FLOAT),
    };
}

/// Draws the descent's world-space effects: the terrain being swallowed.
/// Called once per render frame from `entity.updateEntities()`.
/// The intake particles are spawned from `tick()` instead, so their density does not ride the frame rate.
pub fn drawEffects() void {
    if (!isActive() or !ready) return;
    @setFloatMode(.optimized);

    const fade = intakeFade();
    if (fade <= 0.0) return;

    const zoom = memory.game.camera_scale * zoomFactor();
    drawDebris(fade, @floatCast(zoom));
}

/// Draws each nearby block spiralling into the portal.
fn drawDebris(fade: f32, zoom: f32) void {
    const frame = memory.game.portal_frame;
    const target = anchor;

    for (debris[0..debris_count]) |mote| {
        if (frame < mote.start_frame) continue;
        const travelled: f64 = @floatFromInt(frame - mote.start_frame);
        const u = @min(travelled / @as(f64, @floatFromInt(DEBRIS_TRAVEL)), 1.0);
        const e = u * u; // accelerating, so each block is yanked the last stretch

        const pos: [2]f64 = .{
            mote.start[0] * (1.0 - e) + target[0] * e,
            mote.start[1] * (1.0 - e) + target[1] * e,
        };

        // Shrinking toward nothing as it reaches the mouth sells it being consumed.
        const shrink: f32 = @floatCast(1.0 - 0.8 * e);
        dw.entity.addEntity(.{
            .sprite = mote.sprite,
            .position = worldToScreen(pos),
            .size = dw.CHUNK_SIZE_FLOAT * zoom * shrink,
            .rotation = @floatCast(e * 5.0),
            .lcha = .{ 1.0, 0.05, 4.6, fade * @as(f32, @floatCast(1.0 - e * e)) },
        });
    }
}

/// Emits the portal's inward-falling particles, growing more insistent as the descent builds.
///
/// Deliberately outlives the intake fade: the particles are still going strong while the D+1 layer
/// comes up underneath them, which is what keeps that hand-over from reading as a dissolve.
/// They only thin out over the closing stretch, once the zoom alone carries the shot.
fn spawnIntake() void {
    const t = progress();
    // Ramp in over the intake, hold through the overlay's arrival, then ease away at the very end.
    const ramp = smoothstep(@as(f64, @floatFromInt(memory.game.portal_frame)) / @as(f64, @floatFromInt(fill_deadline)));
    const TAIL_START = 0.8;
    const tail = if (t <= TAIL_START) 1.0 else 1.0 - smoothstep((t - TAIL_START) / (1.0 - TAIL_START));
    const intensity = ramp * tail;
    if (intensity <= 0.0) return;

    const zoom: f32 = @floatCast(memory.game.camera_scale * zoomFactor());
    const count: usize = @intFromFloat(1.0 + 11.0 * intensity);

    dw.particles.spawnInwardRing(worldToScreen(anchor), &PORTAL_COLORS, .{
        .count = count,
        // Held in world scale so the ring hugs the portal as the view zooms in.
        .radius_min = 10.0 * zoom,
        .radius_max = 26.0 * zoom,
        .size_min = 0.8 * zoom,
        .size_max = 2.6 * zoom,
        .travel_min = 10,
        .travel_max = 22,
        .swirl = @floatCast(0.25 + 0.5 * intensity),
    });
}

/// Advances the descent by one logical frame. Called once per tick iteration from `handleTick()`.
pub fn tick() void {
    if (!isActive()) return;
    ensureReady();

    const g = &memory.game;
    g.portal_frame +|= 1;

    if (g.portal_frame >= TOTAL_FRAMES) {
        finish();
        return;
    }

    fillPreview(chunksPerFrame());
    spawnIntake();

    // The world is frozen, so pinning the previous-frame values keeps render interpolation from
    // drifting the view while nothing is actually moving. The descent's own motion is an override.
    g.camera_scale_change = 1.0;
    g.last_camera_pos = g.camera_pos;
    g.last_player_pos = g.player_pos;
}

/// Commits the descent: D+1 stops being a preview and becomes the world.
fn finish() void {
    const g = &memory.game;
    ensureReady();
    world.commitLayer(transition);

    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();

    // The zoom multiplier drops back to 1 with the descent over, and D+1 at the committed scale shows
    // exactly what D showed at a full ZOOM_FACTOR, so the view carries straight through.
    g.camera_scale_change = 1.0;
    dw.mining.selected_hp = 255;
    dw.mouse.mouse_chunk_coord = null;
}

/// Drops the preview buffer and forgets the derived state.
fn releasePreview() void {
    freeBuffers();
    preview_w = 0;
    preview_h = 0;
    filled = 0;
    debris_count = 0;
    ready = false;
}

/// Rebuilds everything a descent needs that a save does not carry, then brings the preview fully up to
/// date in one go. Called after a load; the frame counter alone decides what the player sees next.
pub fn restore() void {
    ready = false;
    if (!isActive()) {
        releasePreview();
        return;
    }
    ensureReady();
    // A load is allowed to be slow, so the buffer is filled outright rather than over the frames that
    // would ordinarily have done it (those frames are already in the past).
    fillPreview(@intCast(preview.len));
}

/// Abandons any running descent and releases its memory. Used when a world is torn down.
pub fn reset() void {
    const g = &memory.game;
    g.portal_phase = @intFromEnum(Phase.idle);
    g.portal_frame = 0;
    releasePreview();
}
